//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.14 at 11:58:37 AM EDT 
//


package com.soapboxrace.jaxb.http;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginAnnouncementContext.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LoginAnnouncementContext">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NotApplicable"/>
 *     &lt;enumeration value="CarPurchase"/>
 *     &lt;enumeration value="CardsPack"/>
 *     &lt;enumeration value="PaintShop"/>
 *     &lt;enumeration value="PerformanceShop"/>
 *     &lt;enumeration value="AftermarketShop"/>
 *     &lt;enumeration value="VinylShop"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LoginAnnouncementContext")
@XmlEnum
public enum LoginAnnouncementContext {

    @XmlEnumValue("NotApplicable")
    NOT_APPLICABLE("NotApplicable"),
    @XmlEnumValue("CarPurchase")
    CAR_PURCHASE("CarPurchase"),
    @XmlEnumValue("CardsPack")
    CARDS_PACK("CardsPack"),
    @XmlEnumValue("PaintShop")
    PAINT_SHOP("PaintShop"),
    @XmlEnumValue("PerformanceShop")
    PERFORMANCE_SHOP("PerformanceShop"),
    @XmlEnumValue("AftermarketShop")
    AFTERMARKET_SHOP("AftermarketShop"),
    @XmlEnumValue("VinylShop")
    VINYL_SHOP("VinylShop");
    private final String value;

    LoginAnnouncementContext(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LoginAnnouncementContext fromValue(String v) {
        for (LoginAnnouncementContext c: LoginAnnouncementContext.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
