//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.14 at 11:58:37 AM EDT 
//


package com.soapboxrace.jaxb.http;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginAnnouncementsDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginAnnouncementsDefinition">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Announcements" type="{}ArrayOfLoginAnnouncementDefinition" minOccurs="0"/>
 *         &lt;element name="ImagesPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginAnnouncementsDefinition", propOrder = {
    "announcements",
    "imagesPath"
})
public class LoginAnnouncementsDefinition {

    @XmlElement(name = "Announcements")
    protected ArrayOfLoginAnnouncementDefinition announcements;
    @XmlElement(name = "ImagesPath")
    protected String imagesPath;

    /**
     * Gets the value of the announcements property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLoginAnnouncementDefinition }
     *     
     */
    public ArrayOfLoginAnnouncementDefinition getAnnouncements() {
        return announcements;
    }

    /**
     * Sets the value of the announcements property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLoginAnnouncementDefinition }
     *     
     */
    public void setAnnouncements(ArrayOfLoginAnnouncementDefinition value) {
        this.announcements = value;
    }

    /**
     * Gets the value of the imagesPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImagesPath() {
        return imagesPath;
    }

    /**
     * Sets the value of the imagesPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImagesPath(String value) {
        this.imagesPath = value;
    }

}
