//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.14 at 11:58:37 AM EDT 
//


package com.soapboxrace.jaxb.http;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PersonaFriendsList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonaFriendsList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="friendPersona" type="{}ArrayOfFriendPersona" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonaFriendsList", propOrder = {
    "friendPersona"
})
public class PersonaFriendsList {

    protected ArrayOfFriendPersona friendPersona;

    /**
     * Gets the value of the friendPersona property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfFriendPersona }
     *     
     */
    public ArrayOfFriendPersona getFriendPersona() {
        return friendPersona;
    }

    /**
     * Sets the value of the friendPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfFriendPersona }
     *     
     */
    public void setFriendPersona(ArrayOfFriendPersona value) {
        this.friendPersona = value;
    }

}
