//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.14 at 11:58:37 AM EDT 
//


package com.soapboxrace.jaxb.http;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="defaultPersonaIdx" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="personas" type="{}ArrayOfProfileData" minOccurs="0"/>
 *         &lt;element name="user" type="{}User" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserInfo", propOrder = {
    "defaultPersonaIdx",
    "personas",
    "user"
})
public class UserInfo {

    protected int defaultPersonaIdx;
    protected ArrayOfProfileData personas;
    protected User user;

    /**
     * Gets the value of the defaultPersonaIdx property.
     * 
     */
    public int getDefaultPersonaIdx() {
        return defaultPersonaIdx;
    }

    /**
     * Sets the value of the defaultPersonaIdx property.
     * 
     */
    public void setDefaultPersonaIdx(int value) {
        this.defaultPersonaIdx = value;
    }

    /**
     * Gets the value of the personas property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfProfileData }
     *     
     */
    public ArrayOfProfileData getPersonas() {
        return personas;
    }

    /**
     * Sets the value of the personas property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfProfileData }
     *     
     */
    public void setPersonas(ArrayOfProfileData value) {
        this.personas = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

}
