ALTER TABLE ONLINE_USERS MODIFY COLUMN numberOfUsers BIGINT NOT NULL;
ALTER TABLE ONLINE_USERS RENAME COLUMN numberOfUsers TO numberOfOnline;
ALTER TABLE ONLINE_USERS
    ADD COLUMN numberOfRegistered BIGINT NOT NULL;