-- Enable cascading deletion for car-related records
ALTER TABLE OWNEDCAR
    DROP FOREIGN KEY FK9i0ql538ftgc26i0eri8keeqp;
ALTER TABLE OWNEDCAR
    DROP FOREIGN KEY FK_OWNEDCAR_CARSLOT;
ALTER TABLE OWNEDCAR
    ADD CONSTRAINT FK_OWNEDCAR_CARSLOT FOREIGN KEY (carSlotId) REFERENCES CARSLOT (id) ON DELETE CASCADE;

ALTER TABLE CUSTOMCAR
    DROP FOREIGN KEY FKjgdh4g5me6ljh5srjkn2t0i71;
ALTER TABLE CUSTOMCAR
    DROP FOREIGN KEY FK_CUSTOMCAR_OWNEDCAR;
ALTER TABLE CUSTOMCAR
    ADD CONSTRAINT FK_CUSTOMCAR_OWNEDCAR
        FOREIGN KEY (ownedCarId) REFERENCES OWNEDCAR (id)
            ON DELETE CASCADE;

ALTER TABLE PAINT
    DROP FOREIGN KEY FKpxxc02fcm311w9odwx6j6wu6u;
ALTER TABLE PAINT
    DROP FOREIGN KEY FK_PAINT_CUSTOMCAR;
ALTER TABLE PAINT
    ADD CONSTRAINT FK_PAINT_CUSTOMCAR
        FOREIGN KEY (customCarId) REFERENCES CUSTOMCAR (id)
            ON DELETE CASCADE;

ALTER TABLE PERFORMANCEPART
    DROP FOREIGN KEY FKbehavbux872md9t4uedp5xw68;
ALTER TABLE PERFORMANCEPART
    DROP FOREIGN KEY FK_PERFPART_CUSTOMCAR;
ALTER TABLE PERFORMANCEPART
    ADD CONSTRAINT FK_PERFPART_CUSTOMCAR
        FOREIGN KEY (customCarId) REFERENCES CUSTOMCAR (id)
            ON DELETE CASCADE;

ALTER TABLE SKILLMODPART
    DROP FOREIGN KEY FK8hnhp2he4tg3rxtpyad7payt1;
ALTER TABLE SKILLMODPART
    DROP FOREIGN KEY FK_SKILLPART_CUSTOMCAR;
ALTER TABLE SKILLMODPART
    ADD CONSTRAINT FK_SKILLPART_CUSTOMCAR
        FOREIGN KEY (customCarId) REFERENCES CUSTOMCAR (id)
            ON DELETE CASCADE;

ALTER TABLE VINYL
    DROP FOREIGN KEY FK83pxksxc4fx2efkwnpqet3f3l;
ALTER TABLE VINYL
    DROP FOREIGN KEY FK_VINYL_CUSTOMCAR;
ALTER TABLE VINYL
    ADD CONSTRAINT FK_VINYL_CUSTOMCAR
        FOREIGN KEY (customCarId) REFERENCES CUSTOMCAR (id)
            ON DELETE CASCADE;

ALTER TABLE VISUALPART
    DROP FOREIGN KEY FK_VISUALPART_CUSTOMCAR;
ALTER TABLE VISUALPART
    ADD CONSTRAINT FK_VISUALPART_CUSTOMCAR
        FOREIGN KEY (customCarId) REFERENCES CUSTOMCAR (id)
            ON DELETE CASCADE;