# This script should fix the absolutely abysmal situation with foreign key constraints in the DB

# ACHIEVEMENT table
ALTER TABLE ACHIEVEMENT
    DROP FOREIGN KEY FK6xo8y7evmxkq6rbqgqlngxnxh;
ALTER TABLE ACHIEVEMENT
    DROP KEY UK_so6kbq2i8oy15k8f9m7vuylu5;
ALTER TABLE ACHIEVEMENT
    ADD CONSTRAINT FK_ACHIEVEMENT_BADGE_DEFINITION_badge_definition_id FOREIGN KEY (badge_definition_id) REFERENCES BADGE_DEFINITION (ID) ON DELETE CASCADE;
ALTER TABLE ACHIEVEMENT
    ADD CONSTRAINT UK_ACHIEVEMENT_badge_definition_id UNIQUE KEY (badge_definition_id);

# ACHIEVEMENT_RANK table
ALTER TABLE ACHIEVEMENT_RANK
    DROP FOREIGN KEY FK276d2ojf04ey397aixbri1j42;
ALTER TABLE ACHIEVEMENT_RANK
    DROP INDEX FK276d2ojf04ey397aixbri1j42;
ALTER TABLE ACHIEVEMENT_RANK
    ADD CONSTRAINT FK_ACHIEVEMENT_RANK_ACHIEVEMENT_achievement_id FOREIGN KEY (achievement_id) REFERENCES ACHIEVEMENT (ID) ON DELETE CASCADE;

# AMPLIFIERS table
ALTER TABLE AMPLIFIERS
    DROP FOREIGN KEY FK8dw7pn0b32ngrloirp6m9xx5x;
ALTER TABLE AMPLIFIERS
    DROP KEY UK_dpq9a1cdlxuukwbqor9ua1j2a;
ALTER TABLE AMPLIFIERS
    ADD CONSTRAINT FK_AMPLIFIERS_PRODUCT_product_id FOREIGN KEY (product_id) REFERENCES PRODUCT (productId) ON DELETE CASCADE;
ALTER TABLE AMPLIFIERS
    ADD CONSTRAINT UK_AMPLIFIERS_product_id UNIQUE KEY (product_id);

# BAN table
ALTER TABLE BAN
    DROP FOREIGN KEY FKlwawdqh4uid0isnsc9uomdyfx;
ALTER TABLE BAN
    DROP FOREIGN KEY FK_BAN_USER;
ALTER TABLE BAN
    DROP FOREIGN KEY FK_BANNED_BY;
ALTER TABLE BAN
    ADD CONSTRAINT FK_BAN_USER_user_id FOREIGN KEY (user_id) REFERENCES USER (ID) ON DELETE CASCADE;
ALTER TABLE BAN
    ADD CONSTRAINT FK_BAN_PERSONA_banned_by_id FOREIGN KEY (banned_by_id) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# BASKETDEFINITION table
ALTER TABLE BASKETDEFINITION
    ADD CONSTRAINT FK_BASKETDEFINITION_PRODUCT_productId FOREIGN KEY (productId) REFERENCES PRODUCT (productId) ON DELETE CASCADE;

# CARD_PACK_ITEM table
ALTER TABLE CARD_PACK_ITEM
    DROP FOREIGN KEY FK3wo6p0la6hflhtss9iqj5t5h6;
ALTER TABLE CARD_PACK_ITEM
    ADD CONSTRAINT FK_CARD_PACK_ITEM_CARD_PACK_cardPackEntity_ID FOREIGN KEY (cardPackEntity_ID) REFERENCES CARD_PACK (ID) ON DELETE CASCADE;

# CUSTOMCAR table
ALTER TABLE CUSTOMCAR
    DROP FOREIGN KEY FK_CUSTOMCAR_OWNEDCAR;
ALTER TABLE CUSTOMCAR
    DROP INDEX FK_CUSTOMCAR_OWNEDCAR;
ALTER TABLE CUSTOMCAR
    ADD CONSTRAINT FK_CUSTOMCAR_OWNEDCAR_ownedCarId FOREIGN KEY (ownedCarId) REFERENCES OWNEDCAR (id) ON DELETE CASCADE;

# EVENT_DATA table
ALTER TABLE EVENT_DATA
    DROP FOREIGN KEY FKjqbikfyvivd8pf6ke5ke5rv1k;
ALTER TABLE EVENT_DATA
    DROP FOREIGN KEY EVENT_DATA_EVENT_SESSION_ID_fk;
ALTER TABLE EVENT_DATA
    DROP FOREIGN KEY EVENT_DATA_PERSONA_ID_fk;
ALTER TABLE EVENT_DATA
    DROP FOREIGN KEY FK_EVENTDATA_EVENT;
ALTER TABLE EVENT_DATA
    ADD CONSTRAINT FK_EVENT_DATA_EVENT_EVENTID FOREIGN KEY (EVENTID) REFERENCES EVENT (ID) ON DELETE CASCADE;
ALTER TABLE EVENT_DATA
    ADD CONSTRAINT FK_EVENT_DATA_PERSONA_personaId FOREIGN KEY (personaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;
ALTER TABLE EVENT_DATA
    ADD CONSTRAINT FK_EVENT_DATA_EVENT_SESSION_eventSessionId FOREIGN KEY (eventSessionId) REFERENCES EVENT_SESSION (ID) ON DELETE CASCADE;

# EVENT_SESSION table
ALTER TABLE EVENT_SESSION
    DROP FOREIGN KEY FKj7j77j10kjso12h57nw1vdb1;
ALTER TABLE EVENT_SESSION
    DROP FOREIGN KEY FK_EVENTSESSION_EVENT;
ALTER TABLE EVENT_SESSION
    DROP FOREIGN KEY FK_EVENTSESSION_LOBBY;
ALTER TABLE EVENT_SESSION
    DROP FOREIGN KEY FK_EVENTSESSION_NEXTLOBBY;
ALTER TABLE EVENT_SESSION
    ADD CONSTRAINT FK_EVENT_SESSION_EVENT_EVENTID FOREIGN KEY (EVENTID) REFERENCES EVENT (ID) ON DELETE CASCADE;
ALTER TABLE EVENT_SESSION
    ADD CONSTRAINT FK_EVENT_SESSION_LOBBY_LOBBYID FOREIGN KEY (LOBBYID) REFERENCES LOBBY (ID) ON DELETE CASCADE;
ALTER TABLE EVENT_SESSION
    ADD CONSTRAINT FK_EVENT_SESSION_LOBBY_NEXTLOBBYID FOREIGN KEY (NEXTLOBBYID) REFERENCES LOBBY (ID) ON DELETE CASCADE;

# INVENTORY table
ALTER TABLE INVENTORY
    DROP FOREIGN KEY FK_INVENTORY_PERSONA;
ALTER TABLE INVENTORY
    ADD CONSTRAINT FK_INVENTORY_PERSONA_personaId FOREIGN KEY (personaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# INVENTORY_ITEM table
ALTER TABLE INVENTORY_ITEM
    DROP FOREIGN KEY FK1ii2plfjt9hme45210mfpr15e;
ALTER TABLE INVENTORY_ITEM
    DROP FOREIGN KEY FKpt9o6wxhd3m4ufvl7dgifl9l3;
ALTER TABLE INVENTORY_ITEM
    ADD CONSTRAINT FK_INVENTORY_ITEM_PRODUCT_productId FOREIGN KEY (productId) REFERENCES PRODUCT (productId) ON DELETE CASCADE;
ALTER TABLE INVENTORY_ITEM
    ADD CONSTRAINT FK_INVENTORY_ITEM_INVENTORY_inventoryEntity_id FOREIGN KEY (inventoryEntity_id) REFERENCES INVENTORY (id) ON DELETE CASCADE;

# INVITE_TICKET table
ALTER TABLE INVITE_TICKET
    DROP FOREIGN KEY FK3plac3qijtk0ciw43aoro0ogn;
ALTER TABLE INVITE_TICKET
    DROP FOREIGN KEY FK_INVITETICKET_USER;
ALTER TABLE INVITE_TICKET
    DROP INDEX FK_INVITETICKET_USER;
ALTER TABLE INVITE_TICKET
    ADD CONSTRAINT FK_INVITE_TICKET_USER_USERID FOREIGN KEY (USERID) REFERENCES USER (ID) ON DELETE CASCADE;

# LOBBY table
ALTER TABLE LOBBY
    DROP FOREIGN KEY FKig5wp7wc5nuwille2w0hahp77;
ALTER TABLE LOBBY
    DROP FOREIGN KEY FK_LOBBY_EVENT;
ALTER TABLE LOBBY
    DROP INDEX FK_LOBBY_EVENT;

# Note: We're not adding a constraint to personaId, because we want lobbies to stick around even if their creator is deleted.
# Deleting lobbies on persona deletion would lead to disappearing EVENT_DATA records (due to cascading deletes), which could cause confusion.
ALTER TABLE LOBBY
    ADD CONSTRAINT FK_LOBBY_EVENT_EVENTID FOREIGN KEY (EVENTID) REFERENCES EVENT (ID) ON DELETE CASCADE;

# LOBBY_ENTRANT table
ALTER TABLE LOBBY_ENTRANT
    DROP FOREIGN KEY FKn2yjevc0kdgpj7juvn0udr2mn;
ALTER TABLE LOBBY_ENTRANT
    DROP FOREIGN KEY FKqy9gynb01x729yacdubgmjier;
ALTER TABLE LOBBY_ENTRANT
    DROP FOREIGN KEY FK_LOBBYENTRANT_LOBBY;
ALTER TABLE LOBBY_ENTRANT
    DROP FOREIGN KEY FK_LOBBYENTRANT_PERSONA;
ALTER TABLE LOBBY_ENTRANT
    DROP INDEX FK_LOBBYENTRANT_LOBBY;
ALTER TABLE LOBBY_ENTRANT
    DROP INDEX FK_LOBBYENTRANT_PERSONA;
ALTER TABLE LOBBY_ENTRANT
    ADD CONSTRAINT FK_LOBBY_ENTRANT_LOBBY_LOBBYID FOREIGN KEY (LOBBYID) REFERENCES LOBBY (ID) ON DELETE CASCADE;
ALTER TABLE LOBBY_ENTRANT
    ADD CONSTRAINT FK_LOBBY_ENTRANT_PERSONA_PERSONAID FOREIGN KEY (PERSONAID) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# NEWS_ARTICLE table
ALTER TABLE NEWS_ARTICLE
    DROP FOREIGN KEY FK41ahos5r10lc5v0o1ttd3tqt3;
ALTER TABLE NEWS_ARTICLE
    DROP FOREIGN KEY FKrgi3drtymu1h23a4jjgd092yg;
ALTER TABLE NEWS_ARTICLE
    ADD CONSTRAINT FK_NEWS_ARTICLE_PERSONA_referenced_persona_id FOREIGN KEY (referenced_persona_id) REFERENCES PERSONA (ID) ON DELETE CASCADE;
ALTER TABLE NEWS_ARTICLE
    ADD CONSTRAINT FK_NEWS_ARTICLE_PERSONA_persona_id FOREIGN KEY (persona_id) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# PERSONA table
ALTER TABLE PERSONA
    DROP FOREIGN KEY FKon9k3f1y35051t3y7x6ogd6k7;
ALTER TABLE PERSONA
    DROP FOREIGN KEY FK_PERSONA_USER;
ALTER TABLE PERSONA
    DROP INDEX FK_PERSONA_USER;
ALTER TABLE PERSONA
    ADD CONSTRAINT FK_PERSONA_USER_USERID FOREIGN KEY (USERID) REFERENCES USER (ID) ON DELETE CASCADE;

# PERSONA_ACHIEVEMENT table
ALTER TABLE PERSONA_ACHIEVEMENT
    DROP FOREIGN KEY FKi0362rxl6y75pcw9v1n7hmecu;
ALTER TABLE PERSONA_ACHIEVEMENT
    DROP FOREIGN KEY FKmci5vxxoedblsncmosjfbtfxk;
ALTER TABLE PERSONA_ACHIEVEMENT
    ADD CONSTRAINT FK_PERSONA_ACHIEVEMENT_ACHIEVEMENT_achievement_id FOREIGN KEY (achievement_id) REFERENCES ACHIEVEMENT (ID) ON DELETE CASCADE;
ALTER TABLE PERSONA_ACHIEVEMENT
    ADD CONSTRAINT FK_PERSONA_ACHIEVEMENT_PERSONA_persona_id FOREIGN KEY (persona_id) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# PERSONA_ACHIEVEMENT_RANK table
ALTER TABLE PERSONA_ACHIEVEMENT_RANK
    DROP FOREIGN KEY FKbbg8f49c6fgkbwwhe25i2ely0;
ALTER TABLE PERSONA_ACHIEVEMENT_RANK
    DROP FOREIGN KEY FKc1w7mcx2mdb9bg30d0ed5efd9;
ALTER TABLE PERSONA_ACHIEVEMENT_RANK
    ADD CONSTRAINT FK_PERSONA_ACHIEVEMENT_RANK_PERSONA_ACHIEVEMENT_id FOREIGN KEY (persona_achievement_id) REFERENCES PERSONA_ACHIEVEMENT (ID) ON DELETE CASCADE;
ALTER TABLE PERSONA_ACHIEVEMENT_RANK
    ADD CONSTRAINT FK_PERSONA_ACHIEVEMENT_RANK_ACHIEVEMENT_RANK_id FOREIGN KEY (achievement_rank_id) REFERENCES ACHIEVEMENT_RANK (ID) ON DELETE CASCADE;

# PERSONA_BADGE table
ALTER TABLE PERSONA_BADGE
    DROP FOREIGN KEY FK4c2e5u8ymnlh4xc8hiem6uota;
ALTER TABLE PERSONA_BADGE
    DROP FOREIGN KEY FKah3mnx6lcx9mg3ant8n1uorii;
ALTER TABLE PERSONA_BADGE
    ADD CONSTRAINT FK_PERSONA_BADGE_BADGE_DEFINITION_badge_definition_id FOREIGN KEY (badge_definition_id) REFERENCES BADGE_DEFINITION (ID) ON DELETE CASCADE;
ALTER TABLE PERSONA_BADGE
    ADD CONSTRAINT FK_PERSONA_BADGE_PERSONA_persona_id FOREIGN KEY (persona_id) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# PRODUCT table
ALTER TABLE PRODUCT
    DROP FOREIGN KEY FK8obn8l9i769slt8pjub191l52;
ALTER TABLE PRODUCT
    DROP KEY UK_10bw1u87a77ibq6hdbivxp1kp;
ALTER TABLE PRODUCT
    ADD CONSTRAINT FK_PRODUCT_PRODUCT_parentProductId FOREIGN KEY (parentProductId) REFERENCES PRODUCT (id) ON DELETE CASCADE;
ALTER TABLE PRODUCT
    ADD CONSTRAINT UK_PRODUCT_productId UNIQUE KEY (productId);

# PROMO_CODE table
ALTER TABLE PROMO_CODE
    DROP FOREIGN KEY FKf3q30eb9w1j5o89cumpi72gry;
ALTER TABLE PROMO_CODE
    DROP FOREIGN KEY FK_PROMOCODE_USER;
ALTER TABLE PROMO_CODE
    DROP INDEX FK_PROMOCODE_USER;
ALTER TABLE PROMO_CODE
    ADD CONSTRAINT FK_PROMO_CODE_USER_USERID FOREIGN KEY (USERID) REFERENCES USER (ID) ON DELETE CASCADE;

# REWARD_TABLE_ITEM table
ALTER TABLE REWARD_TABLE_ITEM
    DROP FOREIGN KEY FK4qxgxc2phadj0ig58lsepsx9y;
ALTER TABLE REWARD_TABLE_ITEM
    ADD CONSTRAINT FK_REWARD_TABLE_ITEM_REWARD_TABLE_rewardTableEntity_ID FOREIGN KEY (rewardTableEntity_ID) REFERENCES REWARD_TABLE (ID) ON DELETE CASCADE;

# SOCIAL_RELATIONSHIP table
ALTER TABLE SOCIAL_RELATIONSHIP
    DROP FOREIGN KEY FKb9v7qy291m237rtenur72v61l;
ALTER TABLE SOCIAL_RELATIONSHIP
    DROP FOREIGN KEY FKih34hpy2rt97e269pop7ehcwm;
ALTER TABLE SOCIAL_RELATIONSHIP
    ADD CONSTRAINT FK_SOCIAL_RELATIONSHIP_USER_fromUserId FOREIGN KEY (fromUserId) REFERENCES USER (ID) ON DELETE CASCADE;
ALTER TABLE SOCIAL_RELATIONSHIP
    ADD CONSTRAINT FK_SOCIAL_RELATIONSHIP_USER_userId FOREIGN KEY (userId) REFERENCES USER (ID) ON DELETE CASCADE;
ALTER TABLE SOCIAL_RELATIONSHIP
    ADD CONSTRAINT FK_SOCIAL_RELATIONSHIP_PERSONA_remotePersonaId FOREIGN KEY (remotePersonaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# TREASURE_HUNT table
ALTER TABLE TREASURE_HUNT
    DROP FOREIGN KEY TREASURE_HUNT_personaId_PERSONA_fk;
ALTER TABLE TREASURE_HUNT
    ADD CONSTRAINT FK_TREASURE_HUNT_PERSONA_personaId FOREIGN KEY (personaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;

# TREASURE_HUNT_CONFIG table
ALTER TABLE TREASURE_HUNT_CONFIG
    DROP FOREIGN KEY FK5tyssnup3qalmjfmr4q27jpxf;
ALTER TABLE TREASURE_HUNT_CONFIG
    ADD CONSTRAINT FK_TREASURE_HUNT_CONFIG_REWARD_TABLE_reward_table_id FOREIGN KEY (reward_table_id) REFERENCES REWARD_TABLE (ID);

# USED_POWERUP table
ALTER TABLE USED_POWERUP
    DROP FOREIGN KEY event_session_fk;
ALTER TABLE USED_POWERUP
    DROP FOREIGN KEY persona_fk;
ALTER TABLE USED_POWERUP
    DROP INDEX persona_index;
ALTER TABLE USED_POWERUP
    DROP INDEX session_index;
ALTER TABLE USED_POWERUP
    DROP INDEX session_persona_index;

ALTER TABLE USED_POWERUP
    ADD CONSTRAINT FK_USED_POWERUP_EVENT_SESSION_eventSessionId FOREIGN KEY (eventSessionId) REFERENCES EVENT_SESSION (ID) ON DELETE CASCADE;
ALTER TABLE USED_POWERUP
    ADD CONSTRAINT FK_USED_POWERUP_PERSONA_personaId FOREIGN KEY (personaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;