# Wow, 14 migrations already. This one is another big one!
# We're merging CUSTOMCAR into OWNEDCAR, and then renaming OWNEDCAR to CAR.
# Considering every OWNEDCAR should always have exactly one CUSTOMCAR, having separate tables is pretty pointless.

# Copy CUSTOMCAR columns
ALTER TABLE OWNEDCAR
    ADD COLUMN baseCar INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN carClassHash INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN isPreset BIT;
ALTER TABLE OWNEDCAR
    ADD COLUMN `level` INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN `name` VARCHAR(255);
ALTER TABLE OWNEDCAR
    ADD COLUMN physicsProfileHash INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN rating INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN resalePrice FLOAT;
ALTER TABLE OWNEDCAR
    ADD COLUMN rideHeightDrop FLOAT;
ALTER TABLE OWNEDCAR
    ADD COLUMN skillModSlotCount INT;
ALTER TABLE OWNEDCAR
    ADD COLUMN `version` INT;

# Add new relation columns to customization tables
ALTER TABLE PAINT
    ADD COLUMN `carId` BIGINT;
ALTER TABLE PERFORMANCEPART
    ADD COLUMN `carId` BIGINT;
ALTER TABLE SKILLMODPART
    ADD COLUMN `carId` BIGINT;
ALTER TABLE VINYL
    ADD COLUMN `carId` BIGINT;
ALTER TABLE VISUALPART
    ADD COLUMN `carId` BIGINT;

# Sync CUSTOMCAR->OWNEDCAR
UPDATE OWNEDCAR OC
    INNER JOIN CUSTOMCAR CC ON CC.ownedCarId = OC.id
SET OC.baseCar=CC.baseCar,
    OC.carClassHash=CC.carClassHash,
    OC.isPreset=CC.isPreset,
    OC.`level`=CC.`level`,
    OC.`name`=CC.`name`,
    OC.physicsProfileHash=CC.physicsProfileHash,
    OC.rating=CC.rating,
    OC.resalePrice=CC.resalePrice,
    OC.rideHeightDrop=CC.rideHeightDrop,
    OC.skillModSlotCount=CC.skillModSlotCount,
    OC.version=CC.version
WHERE 1 = 1;

# Update EVENT_DATA carId values
UPDATE EVENT_DATA ED
    INNER JOIN CUSTOMCAR CC ON ED.carId = CC.id
SET ED.carId=CC.ownedCarId
WHERE ED.carId != 0;

# Update customization tables
UPDATE PAINT P
    INNER JOIN CUSTOMCAR CC ON CC.id = P.customCarId
SET P.carId=CC.ownedCarId
WHERE P.carId IS NULL;
UPDATE PERFORMANCEPART PP
    INNER JOIN CUSTOMCAR CC ON CC.id = PP.customCarId
SET PP.carId=CC.ownedCarId
WHERE PP.carId IS NULL;
UPDATE SKILLMODPART SMP
    INNER JOIN CUSTOMCAR CC ON CC.id = SMP.customCarId
SET SMP.carId=CC.ownedCarId
WHERE SMP.carId IS NULL;
UPDATE VINYL V
    INNER JOIN CUSTOMCAR CC ON CC.id = V.customCarId
SET V.carId=CC.ownedCarId
WHERE V.carId IS NULL;
UPDATE VISUALPART VP
    INNER JOIN CUSTOMCAR CC ON CC.id = VP.customCarId
SET VP.carId=CC.ownedCarId
WHERE VP.carId IS NULL;

# Fix nullability of new columns
ALTER TABLE OWNEDCAR
    MODIFY COLUMN baseCar INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN carClassHash INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN isPreset BIT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN `level` INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN `name` VARCHAR(255) NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN physicsProfileHash INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN rating INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN resalePrice FLOAT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN rideHeightDrop FLOAT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN skillModSlotCount INT NOT NULL;
ALTER TABLE OWNEDCAR
    MODIFY COLUMN `version` INT NOT NULL;
ALTER TABLE PAINT
    MODIFY COLUMN `carId` BIGINT NOT NULL;
ALTER TABLE PERFORMANCEPART
    MODIFY COLUMN `carId` BIGINT NOT NULL;
ALTER TABLE SKILLMODPART
    MODIFY COLUMN `carId` BIGINT NOT NULL;
ALTER TABLE VINYL
    MODIFY COLUMN `carId` BIGINT NOT NULL;
ALTER TABLE VISUALPART
    MODIFY COLUMN `carId` BIGINT NOT NULL;

# Rename OWNEDCAR to CAR
ALTER TABLE OWNEDCAR RENAME TO CAR;

# Add new constraints and remove old ones
ALTER TABLE PAINT
    DROP FOREIGN KEY FK_PAINT_CUSTOMCAR;
ALTER TABLE PAINT
    DROP INDEX FK_PAINT_CUSTOMCAR;
ALTER TABLE PERFORMANCEPART
    DROP FOREIGN KEY FK_PERFPART_CUSTOMCAR;
ALTER TABLE PERFORMANCEPART
    DROP INDEX FK_PERFPART_CUSTOMCAR;
ALTER TABLE SKILLMODPART
    DROP FOREIGN KEY FK_SKILLPART_CUSTOMCAR;
ALTER TABLE SKILLMODPART
    DROP INDEX FK_SKILLPART_CUSTOMCAR;
ALTER TABLE VINYL
    DROP FOREIGN KEY FK_VINYL_CUSTOMCAR;
ALTER TABLE VINYL
    DROP INDEX FK_VINYL_CUSTOMCAR;
ALTER TABLE VISUALPART
    DROP FOREIGN KEY FK_VISUALPART_CUSTOMCAR;
ALTER TABLE VISUALPART
    DROP INDEX FK_VISUALPART_CUSTOMCAR;

ALTER TABLE PAINT
    DROP COLUMN customCarId;
ALTER TABLE PAINT
    ADD CONSTRAINT FK_PAINT_CAR_carId FOREIGN KEY (carId) REFERENCES CAR (id) ON DELETE CASCADE;
ALTER TABLE PERFORMANCEPART
    DROP COLUMN customCarId;
ALTER TABLE PERFORMANCEPART
    ADD CONSTRAINT FK_PERFORMANCEPART_CAR_carId FOREIGN KEY (carId) REFERENCES CAR (id) ON DELETE CASCADE;
ALTER TABLE SKILLMODPART
    DROP COLUMN customCarId;
ALTER TABLE SKILLMODPART
    ADD CONSTRAINT FK_SKILLMODPART_CAR_carId FOREIGN KEY (carId) REFERENCES CAR (id) ON DELETE CASCADE;
ALTER TABLE VINYL
    DROP COLUMN customCarId;
ALTER TABLE VINYL
    ADD CONSTRAINT FK_VINYL_CAR_carId FOREIGN KEY (carId) REFERENCES CAR (id) ON DELETE CASCADE;
ALTER TABLE VISUALPART
    DROP COLUMN customCarId;
ALTER TABLE VISUALPART
    ADD CONSTRAINT FK_VISUALPART_CAR_carId FOREIGN KEY (carId) REFERENCES CAR (id) ON DELETE CASCADE;

ALTER TABLE CAR
    DROP FOREIGN KEY FK_OWNEDCAR_PERSONA_personaId;
ALTER TABLE CAR
    DROP INDEX FK_OWNEDCAR_PERSONA_personaId;
ALTER TABLE CAR
    ADD CONSTRAINT FK_CAR_PERSONA_personaId FOREIGN KEY (personaId) REFERENCES PERSONA (ID) ON DELETE CASCADE;
ALTER TABLE CAR
    DROP INDEX OWNEDCAR_expirationDate_index;
ALTER TABLE CAR
    DROP INDEX OWNEDCAR_ownershipType_index;
ALTER TABLE CAR
    ADD INDEX IDX_CAR_expirationDate (expirationDate ASC);
ALTER TABLE CAR
    ADD INDEX IDX_CAR_ownershipType (ownershipType ASC);

# Cleanup
DROP TABLE CUSTOMCAR;