INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (1, '20136', '', '', 0, '', 465216261, '', 'Holiday_Snowman_Gift_Vinyl', 2, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (2, '20136', '', '', 0, '', 1060694561, '', 'Holiday_Winter', 20, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (3, '20136', '', '', 0, '', 1228911631, '', 'Holiday_Festive_Vinyl', 21, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (4, '20136', '', '', 0, '', 1421960358, '', 'Holiday_d_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (5, '20136', '', '', 0, '', -1234247139, '', 'Holiday_Giftwrap_Vinyl', 19, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (6, '20136', '', '', 0, '', -308850777, '', 'Holiday_Girl_Vinyl', 1, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (7, '20136', '', '', 0, '', 258225347, '', 'GameStop_Vinyls', 3, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (8, '20136', '', '', 0, '', 292603680, '', 'Chinese_New_Year_2013_Vinyls', 23, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (9, '20136', '', '', 0, '', -2117925458, '', 'Holiday_Valentine', 24, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (10, '20136', '', '', 0, '', 732138705, '', 'Holiday_2013_Spring_Vinyl', 25, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (11, '20136', '', '', 0, '', 732138705, '', 'Holiday_2013_Spring_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (12, '20136', '', '', 0, '', 1310612, '', 'Cops', 28, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (13, '20136', '', '', 0, '', -1520549515, '', 'PROSTREET_NOISEBOMB_VINYL', 46, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (14, '20136', '', '', 0, '', 776405284, '', 'Alphabet_Upper_Lower_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (15, '20136', '', '', 0, '', 1333978540, '', 'Alphabet_Special_Case_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (16, '20136', '', '', 0, '', -1313207994, '', 'AUDI_Vinyls', 33, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (17, '20136', '', '', 0, '', 938968009, '', 'BMW_Vinyls', 34, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (18, '20136', '', '', 0, '', -2147002961, '', 'CHEVROLET_VINYLS', 35, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (19, '20136', '', '', 0, '', 1186951366, '', 'DODGE_Vinyls', 36, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (20, '20136', '', '', 0, '', -170970514, '', 'FORD_Vinyls', 37, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (21, '20136', '', '', 0, '', 952533007, '', 'Lamborghini_Vinyls', 38, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (22, '20136', '', '', 0, '', 1037191832, '', 'NISSIAN_Vinyls', 39, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (23, '20136', '', '', 0, '', 678481367, '', 'Porsche_Vinyls', 40, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (24, '20136', '', '', 0, '', 451662628, '', 'VOLKSWAGEN_Vinyls', 41, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (25, '20136', '', '', 0, '', 1516934767, '', 'Bumper_Sticker_Vinyl', 32, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (26, '20136', '', '', 0, '', 1636921707, '', 'Tribal_Nomad', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (27, '20136', '', '', 0, '', -930928800, '', 'Special', 29, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (28, '20136', '', '', 0, '', -709890944, '', 'Primitives_Eikon', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (29, '20136', '', '', 0, '', 1630954120, '', 'Tribal_Inkee', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (30, '20136', '', '', 0, '', 1722573741, '', 'PROSTREET_SUPERPROMOTION_VINYL', 45, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (31, '20136', '', '', 0, '', -1581360948, '', 'Urban_Vandal', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (32, '20136', '', '', 0, '', 1209488594, '', 'Flames_Kerosene', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (33, '20136', '', '', 0, '', 975375463, '', 'Numbers_Tiotal', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (34, '20136', '', '', 0, '', -1833288533, '', 'PROSTREET_GEFFECT_VINYL', 42, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (35, '20136', '', '', 0, '', -1856230184, '', 'PROSTREET_NITROCIDE_VINYL', 43, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (36, '20136', '', '', 0, '', -1580232310, '', 'PROSTREET_ROGUESPEED_VINYL', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (37, '20136', '', '', 0, '', 861708167, '', 'Holiday_Halloween', 27, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (38, '20136', '', '', 0, '', -630819107, '', 'Pinstriping_Hatch', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (39, '20136', '', '', 0, '', -1677520347, '', 'Primitives_Linear', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (40, '20136', '', '', 0, '', -728659978, '', 'Camo_Maskirovka', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (41, '20136', '', '', 0, '', -688005155, '', 'Tattoo_Vudu', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (42, '20136', '', '', 0, '', -2123538394, '', 'YEAR2_VINYLS', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (43, '20136', '', '', 0, '', 1077565943, '', 'Numbers_Solo', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (44, '20136', '', '', 0, '', -1405213586, '', 'Primitives_Shapes', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (45, '20136', '', '', 0, '', -427927574, '', 'Chicane', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (46, '20136', '', '', 0, '', -689721571, '', 'Primitives_Visor', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (47, '20136', '', '', 0, '', -1415837085, '', 'Numbers_Meridian', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (48, '20136', '', '', 0, '', -653617830, '', 'Floral_Florcore', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (49, '20136', '', '', 0, '', 1000028150, '', 'Du001_Vinyls', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (50, '20136', '', '', 0, '', 1000028151, '', 'Du001_Vinyls2', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (51, '20136', '', '', 0, '', 2070511318, '', 'Holiday_Snowflakes_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (52, '20136', '', '', 0, '', -824350210, '', 'Holiday_Cinco_De_Mayo_Girl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (53, '20136', '', '', 0, '', -1813129290, '', 'Porsche_Circle_Vinyl_Single', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (54, '20136', '', '', 0, '', -1059168035, '', 'Lamborghini_Single_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (55, '20136', '', '', 0, '', -895494852, '', 'YEAR2_ZL1_VINYLS', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (56, '20136', '', '', 0, '', -995697986, '', 'Amazon_Muscle_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (57, '20136', '', '', 0, '', -152833371, '', 'Amazon_Bronze_Vinyl', 0, '', FALSE, FALSE, '');
INSERT INTO SOAPBOX.CATEGORY (IDCATEGORY, CATALOGVERSION, CATEGORIES, DISPLAYNAME, FILTERTYPE, ICON, ID, LONGDESCRIPTION, NAME, PRIORITY, SHORTDESCRIPTION, SHOWINNAVIGATIONPANE, SHOWPROMOPAGE, WEBICON)
VALUES (58, '20136', '', '', 0, '', -1040085317, '', 'Amazon_Gold_Vinyl', 0, '', FALSE, FALSE, '');
