INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (1,10,'TXT_CHAT_LANG_ENGLISH','EN');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (2,10,'TXT_CHAT_LANG_GERMAN','DE');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (3,10,'TXT_CHAT_LANG_FRENCH','FR');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (4,10,'TXT_CHAT_LANG_SPANISH','ES');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (5,10,'TXT_CHAT_LANG_POLISH','PL');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (6,10,'TXT_CHAT_LANG_BRAZILIANPORTUGUESE','BR');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (7,10,'TXT_CHAT_LANG_RUSSIAN','RU');
INSERT INTO SOAPBOX.CHAT_ROOM (ID,AMOUNT,LONGNAME,SHORTNAME) VALUES (8,10,'TXT_CHAT_LANG_GENERAL','GN');
