INSERT
INTO
    SOAPBOX.PARAMETER VALUES
    (
        'ANNOUNCEMENT_DOMAIN',
        'http://i.imgur.com/'
    ),
    (
        'CASH_REWARD_MULTIPLIER',
        '1'
    )
    ,
    (
        'DRAG_MINIMUM_TIME',
        '10000'
    )
    ,
    (
        'EMAIL_FROM',
        'myemail@gmail.com'
    )
    ,
    (
        'GOOGLE_LB_ENABLED',
        'false'
    )
    ,
    (
        'ENABLE_CAR_DAMAGE',
        'false'
    )
    ,
    (
        'ENABLE_DROP_ITEM',
        'false'
    )
    ,
    (
        'ENABLE_ECONOMY',
        'false'
    )
    ,
    (
        'ENABLE_METONATOR_LAUNCHER_PROTECTION',
        'false'
    )
    ,
    (
        'ENABLE_POWERUP_DECREASE',
        'false'
    )
    ,
    (
        'ENABLE_REPUTATION',
        'false'
    )
    ,
    (
        'ENABLE_TREASURE_HUNT',
        'false'
    )
    ,
    (
        'FREEROAM_JSON_PATH',
        '/tmp/freeroam-map.jsonp'
    )
    ,
    (
        'MAX_CAR_SLOTS_FREE',
        '30'
    )
    ,
    (
        'MAX_CAR_SLOTS_PREMIUM',
        '60'
    )
    ,
    (
        'MAX_ONLINE_PLAYERS',
        '50'
    )
    ,
    (
        'MAX_PLAYER_CASH_FREE',
        '5000000'
    )
    ,
    (
        'MAX_PLAYER_CASH_PREMIUM',
        '8500000'
    )
    ,
    (
        'OPENFIRE_ADDRESS',
        'http://localhost:9090/plugins/restapi/v1'
    )
    ,
    (
        'OPENFIRE_TOKEN',
        'xzxzx99df4d51z2d'
    )
    ,
    (
        'PREMIUM_CARCHANGER_PROTECTION',
        'false'
    )
    ,
    (
        'PROMO_CODE_TOKEN',
        '12345678'
    )
    ,
    (
        'PURSUIT_MINIMUM_TIME',
        '18500'
    ),
    ('PURSUIT_COP_CARS_DEPLOYED_CASH_MULTIPLIER','0.1'),
	('PURSUIT_COP_CARS_DEPLOYED_REP_MULTIPLIER','0.1'),
	('PURSUIT_COP_CARS_DISABLED_CASH_MULTIPLIER','0.1'),
	('PURSUIT_COP_CARS_DISABLED_REP_MULTIPLIER','0.1'),
	('PURSUIT_COP_CARS_RAMMED_CASH_MULTIPLIER','0.1'),
	('PURSUIT_COP_CARS_RAMMED_REP_MULTIPLIER','0.1'),
	('PURSUIT_COST_TO_STATE_CASH_MULTIPLIER','0.00001'),
	('PURSUIT_COST_TO_STATE_REP_MULTIPLIER','0.00001'),
	('PURSUIT_INFRACTIONS_CASH_MULTIPLIER','0.0001'),
	('PURSUIT_INFRACTIONS_REP_MULTIPLIER','0.0001'),
	('PURSUIT_ROADBLOCKS_DODGED_CASH_MULTIPLIER','0.1'),
	('PURSUIT_ROADBLOCKS_DODGED_REP_MULTIPLIER','0.1'),
	('PURSUIT_SPIKE_STRIPS_DODGED_CASH_MULTIPLIER','0.1'),
	('PURSUIT_SPIKE_STRIPS_DODGED_REP_MULTIPLIER','0.1'),
	('PURSUIT_PURSUIT_LENGTH_CASH_MULTIPLIER','0.0000001'),
	('PURSUIT_PURSUIT_LENGTH_REP_MULTIPLIER','0.0000001'),
	('PURSUIT_HEAT_LEVEL_CASH_MULTIPLIER','0.1'),
	('PURSUIT_HEAT_LEVEL_REP_MULTIPLIER','0.1')
	,
    (
        'ROUTE_MINIMUM_TIME',
        '50000'
    )
    ,
    (
        'SERVER_ADDRESS',
        'http://127.0.0.1:8680'
    )
    ,
    (
        'STARTING_CASH_AMOUNT',
        '5000000'
    )
    ,
    (
        'STARTING_INVENTORY_PERF_SLOTS',
        '100'
    )
    ,
    (
        'STARTING_INVENTORY_SKILL_SLOTS',
        '150'
    )
    ,
    (
        'STARTING_INVENTORY_VISUAL_SLOTS',
        '200'
    )
    ,
    (
        'STARTING_LEVEL_NUMBER',
        '60'
    )
    ,
    ('TH_BASE_REP','1000'),
    ('TH_BASE_CASH','200'),
    ('TH_REP_MULTIPLIER','0.1'),
    ('TH_CASH_MULTIPLIER','0.1'),
    ('TH_DAY_REP_MULTIPLIER','100'),
    ('TH_DAY_CASH_MULTIPLIER','100')
    ,
    (
        'TE_MINIMUM_TIME',
        '60000'
    )
    ,
    (
        'TICKET_TOKEN',
        null
    )
    ,
    (
        'UDP_FREEROAM_IP',
        '127.0.0.1'
    )
    ,
    (
        'UDP_FREEROAM_PASSWORD',
        null
    )
    ,
    (
        'UDP_FREEROAM_PORT',
        '9999'
    )
    ,
    (
        'UDP_RACE_IP',
        '127.0.0.1'
    )
    ,
    (
        'UDP_RACE_PASSWORD',
        null
    )
    ,
    (
        'UDP_RACE_PORT',
        '9998'
    )
    ,
    (
        'USE_FORWARDED_FOR',
        'false'
    )
    ,
    (
        'XMPP_IP',
        '127.0.0.1'
    )
    ,
    (
        'XMPP_PORT',
        '5222'
    );