INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (3, 9, 1, 70, 0, 999, TRUE, FALSE, 'Bristol & Diamond (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (5, 4, 1, 70, 0, 999, TRUE, FALSE, 'Campus Interchange (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (6, 4, 1, 70, 0, 999, TRUE, FALSE, 'Country Club; Campus Interchange Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (7, 4, 1, 70, 0, 999, TRUE, FALSE, 'Oil Refinery (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (8, 9, 1, 70, 0, 999, TRUE, FALSE, 'Ironhorse & Coast (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (9, 4, 1, 70, 0, 999, TRUE, FALSE, 'Camden Tunnel (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (10, 4, 1, 70, 0, 999, TRUE, FALSE, 'Bay Bridge; Camden Tunnel Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (11, 4, 1, 70, 0, 999, TRUE, FALSE, 'Waterfront (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (12, 4, 1, 70, 0, 999, TRUE, FALSE, 'Gray Point (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (13, 9, 1, 70, 0, 999, TRUE, FALSE, 'State & Warrent (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (14, 9, 1, 70, 0, 999, TRUE, FALSE, 'Station & Fisher (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (15, 4, 1, 70, 0, 999, TRUE, FALSE, 'Route 55; Gray Point Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (16, 9, 1, 70, 0, 999, TRUE, FALSE, 'Stadium & Chase (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (17, 9, 1, 70, 0, 999, TRUE, FALSE, 'Heritage & Diamond (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (18, 9, 1, 70, 0, 999, TRUE, FALSE, 'Camden & Route 55 (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (19, 9, 1, 70, 0, 999, TRUE, FALSE, 'North Bay & Harbour (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (20, 9, 1, 70, 0, 999, TRUE, FALSE, 'Stadium & Hwy 1 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (21, 4, 1, 70, 0, 999, TRUE, FALSE, 'College Asylum (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (22, 9, 1, 70, 0, 999, TRUE, FALSE, 'Boundary & Marina (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (23, 4, 1, 70, 0, 999, TRUE, FALSE, 'Park Boundary (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (24, 4, 1, 70, 0, 999, TRUE, FALSE, 'College Mall; College Asylum Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (25, 9, 1, 70, 0, 999, TRUE, FALSE, 'Beacon & Station (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (26, 9, 1, 70, 0, 999, TRUE, FALSE, 'Bristol & Bayshore (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (27, 9, 1, 70, 0, 999, TRUE, FALSE, 'Chancellor & Campus (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (28, 9, 1, 70, 0, 999, TRUE, FALSE, 'Rockridge & Union (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (29, 9, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood & Lyons (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (30, 9, 1, 70, 0, 999, TRUE, FALSE, 'Union & Holls (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (31, 9, 1, 70, 0, 999, TRUE, FALSE, 'Heritage & Campus (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (32, 4, 1, 70, 0, 999, TRUE, FALSE, 'Heritage Heights (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (33, 9, 1, 70, 0, 999, TRUE, FALSE, 'Hwy 99 & State (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (34, 9, 1, 70, 0, 999, TRUE, FALSE, 'Clubhouse & Hollis (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (35, 9, 1, 70, 0, 999, TRUE, FALSE, 'Stadium & Hwy 99 (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (36, 4, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood College (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (37, 4, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood Park Loop (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (38, 4, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood Central (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (39, 9, 1, 70, 0, 999, TRUE, FALSE, 'Diamond & Union (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (41, 9, 1, 70, 0, 999, TRUE, FALSE, 'Chinatown Delivery (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (43, 9, 1, 70, 0, 999, TRUE, FALSE, 'Construction Route (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (45, 9, 1, 70, 0, 999, TRUE, FALSE, 'Welcome to Palmont (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (47, 9, 1, 70, 0, 999, TRUE, FALSE, 'Old Quarter (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (49, 4, 1, 70, 0, 999, TRUE, FALSE, 'Savannah Street (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (50, 4, 1, 70, 0, 999, TRUE, FALSE, 'North Broadway (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (51, 9, 1, 70, 0, 999, TRUE, FALSE, 'Silverton Way (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (52, 4, 1, 70, 0, 999, TRUE, FALSE, 'Lucky Towers (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (53, 9, 1, 70, 0, 999, TRUE, FALSE, 'Starlight Street (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (54, 9, 1, 70, 0, 999, TRUE, FALSE, 'Spade Street (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (55, 4, 1, 70, 0, 999, TRUE, FALSE, 'Paradise Hotel (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (56, 9, 1, 70, 0, 999, TRUE, FALSE, 'Eagle Drive (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (57, 4, 1, 70, 0, 999, TRUE, FALSE, 'Brooks Street (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (60, 22, 1, 70, 0, 999, TRUE, FALSE, 'Stadium (Meeting Place)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (61, 4, 1, 70, 0, 999, TRUE, FALSE, 'Downtown Challenge (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (72, 4, 1, 70, 0, 999, TRUE, FALSE, 'Campbell Tunnel (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (76, 4, 1, 70, 0, 999, TRUE, FALSE, 'North Road (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (77, 4, 1, 70, 0, 999, TRUE, FALSE, 'Silk Road (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (78, 9, 1, 70, 0, 999, TRUE, FALSE, 'Chinatown Tram (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (79, 4, 1, 70, 0, 999, TRUE, FALSE, 'Main Street (Circuit) - Uncompleted Mini-Map');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (80, 9, 1, 70, 0, 999, TRUE, FALSE, 'Lincoln Boulevard (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (81, 9, 1, 70, 0, 999, TRUE, FALSE, 'Mason Street (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (82, 4, 1, 70, 0, 999, TRUE, FALSE, 'Garden Boulevard (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (83, 4, 1, 70, 0, 999, TRUE, FALSE, 'Hastings (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (85, 9, 1, 70, 0, 999, TRUE, FALSE, 'West Park & Forest (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (97, 9, 1, 70, 0, 999, TRUE, FALSE, 'Riverfront & Green (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (98, 9, 1, 70, 0, 999, TRUE, FALSE, 'Seaside Interchange (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (108, 4, 1, 70, 0, 999, TRUE, FALSE, 'Omega Industries (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (120, 9, 1, 70, 0, 999, TRUE, FALSE, 'Lion Challenge (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (131, 9, 1, 70, 0, 999, TRUE, FALSE, 'Valley & State (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (133, 4, 1, 70, 0, 999, TRUE, FALSE, 'Iron Horse (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (135, 9, 1, 70, 0, 999, TRUE, FALSE, 'East Park (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (144, 4, 1, 70, 0, 999, TRUE, FALSE, 'College Loop; Rosewood College Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (145, 4, 1, 70, 0, 999, TRUE, FALSE, 'Little Italy (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (146, 9, 1, 70, 0, 999, TRUE, FALSE, 'Lyons & Hwy 201 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (147, 9, 1, 70, 0, 999, TRUE, FALSE, 'West Park & Lyons (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (148, 9, 1, 70, 0, 999, TRUE, FALSE, 'Bond & Country Club (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (157, 4, 1, 70, 0, 999, TRUE, FALSE, 'Financial District (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (158, 9, 1, 70, 0, 999, TRUE, FALSE, 'Interchange & Bond (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (219, 9, 1, 70, 0, 999, TRUE, FALSE, 'Downtown Run (Sprint) - Very small track >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (252, 4, 1, 70, 0, 999, TRUE, FALSE, 'Route 21 (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (277, 9, 1, 70, 0, 999, TRUE, FALSE, 'Mason St Bridge (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (279, 4, 1, 70, 0, 999, TRUE, FALSE, 'Robinson Bay (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (280, 4, 1, 70, 0, 999, TRUE, FALSE, 'South Fortuna Circuit (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (287, 4, 1, 70, 0, 999, TRUE, FALSE, 'University Way (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (289, 4, 1, 70, 0, 999, TRUE, FALSE, 'Skyline Avenue (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (290, 9, 1, 70, 0, 999, TRUE, FALSE, 'Verona Tunnel (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (292, 9, 1, 70, 0, 999, TRUE, FALSE, 'North Bellezza (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (295, 4, 1, 70, 0, 999, TRUE, FALSE, 'Ocean View (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (296, 9, 1, 70, 0, 999, TRUE, FALSE, 'York Road (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (298, 4, 1, 70, 0, 999, TRUE, FALSE, 'Condo Row (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (299, 9, 1, 70, 0, 999, TRUE, FALSE, 'Agostini Avenue (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (302, 4, 1, 70, 0, 999, TRUE, FALSE, 'Beachfront (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (303, 4, 1, 70, 0, 999, TRUE, FALSE, 'Dover & Lepus (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (305, 9, 1, 70, 0, 999, TRUE, FALSE, 'Waterfront Road (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (307, 4, 1, 70, 0, 999, TRUE, FALSE, 'Dover Street (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (308, 4, 1, 70, 0, 999, TRUE, FALSE, 'Kempton Docks (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (309, 9, 1, 70, 0, 999, TRUE, FALSE, 'Petersburg Dam (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (314, 9, 1, 70, 0, 999, TRUE, FALSE, 'Mission Street (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (317, 4, 1, 70, 0, 999, TRUE, FALSE, 'Central Coast (Circuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (357, 24, 1, 70, 0, 999, TRUE, FALSE, 'Home Run (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (359, 4, 1, 70, 0, 999, TRUE, FALSE, 'De Vellis Drive (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (360, 4, 1, 70, 0, 999, TRUE, FALSE, 'Camden Hills (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (362, 4, 1, 70, 0, 999, TRUE, FALSE, 'Welcome to Oktoberfest (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (366, 4, 1, 70, 0, 999, TRUE, FALSE, 'Top Gear Challenge; De Vellis Drive Reverse (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (367, 9, 1, 70, 0, 999, TRUE, FALSE, 'Ghostwood (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (368, 24, 1, 70, 0, 999, TRUE, FALSE, 'Late Departure (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (370, 24, 1, 70, 0, 999, TRUE, FALSE, 'Compromised (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (374, 22, 1, 70, 0, 999, TRUE, FALSE, 'Overlook (Meeting Place)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (375, 24, 1, 70, 0, 999, TRUE, FALSE, 'All In (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (376, 24, 1, 70, 0, 999, TRUE, FALSE, 'Most Wanted (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (377, 24, 1, 70, 0, 999, TRUE, FALSE, 'Outlaws (Team Escape)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (378, 22, 1, 70, 0, 999, TRUE, FALSE, 'Riverfront Stadium (Meeting Place)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (379, 9, 1, 70, 0, 999, TRUE, FALSE, 'Home for the Holidays (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (383, 12, 1, 70, 0, 999, TRUE, FALSE, 'Fortuna Pursuit (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (384, 12, 1, 70, 0, 999, TRUE, FALSE, 'Kempton Pursuit (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (385, 12, 1, 70, 0, 999, TRUE, FALSE, 'Palmont Pursuit (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (386, 12, 1, 70, 0, 999, TRUE, FALSE, 'Silverton Showdown (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (387, 12, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood Raid (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (388, 12, 1, 70, 0, 999, TRUE, FALSE, 'Rockport Resistance (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (389, 12, 1, 70, 0, 999, TRUE, FALSE, 'Camden Pursuit (Pursuit)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (392, 24, 1, 70, 0, 999, TRUE, FALSE, 'Underground (Team Escape, 2 Racers)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (393, 24, 1, 70, 0, 999, TRUE, FALSE, 'High Stakes (Team Escape, 2 Racers)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (499, 19, 1, 70, 0, 999, TRUE, FALSE, 'Backwood Split (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (500, 19, 1, 70, 0, 999, TRUE, FALSE, 'Breakneck (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (501, 19, 1, 70, 0, 999, TRUE, FALSE, 'Speed Fair (Drag) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (502, 19, 1, 70, 0, 999, TRUE, FALSE, 'Rockport Turnpike (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (503, 19, 1, 70, 0, 999, TRUE, FALSE, 'Arch Rush (Drag) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (504, 19, 1, 70, 0, 999, TRUE, FALSE, 'Neon Crossroads (Drag, Traffic)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (506, 19, 1, 70, 0, 999, TRUE, FALSE, 'Chinatown Showdown (Drag, Traffic)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (507, 19, 1, 70, 0, 999, TRUE, FALSE, 'Tram Underpass (Drag) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (509, 19, 1, 70, 0, 999, TRUE, FALSE, 'Breaking Point (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (510, 19, 1, 70, 0, 999, TRUE, FALSE, 'Burrows (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (511, 19, 1, 70, 0, 999, TRUE, FALSE, 'Hwy 142 (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (513, 19, 1, 70, 0, 999, TRUE, FALSE, 'Gridlock (Drag, Traffic) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (515, 19, 1, 70, 0, 999, TRUE, FALSE, 'Skirmish (Drag)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (516, 19, 1, 70, 0, 999, TRUE, FALSE, 'Runway (Drag) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (517, 19, 1, 70, 0, 999, TRUE, FALSE, 'Loop (Drag) - 2 Racers');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (521, 4, 1, 70, 0, 999, TRUE, FALSE, 'Lunar Circuit (Circuit) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (525, 19, 1, 70, 0, 999, TRUE, FALSE, 'Downturn (Drag, Traffic) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (526, 9, 1, 70, 0, 999, TRUE, FALSE, 'Rosewood Rally (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (529, 9, 1, 70, 0, 999, TRUE, FALSE, 'Lincoln Boulevard Reverse 02 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (530, 9, 1, 70, 0, 999, TRUE, FALSE, 'Welcome to Palmont Reverse 03 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (531, 9, 1, 70, 0, 999, TRUE, FALSE, 'Old Quarter Reverse 04 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (532, 9, 1, 70, 0, 999, TRUE, FALSE, 'Hwy 99 & State Reverse 05 (Sprint)');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (533, 9, 1, 70, 0, 999, TRUE, FALSE, 'Petersburg Dam Reverse 06 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (534, 9, 1, 70, 0, 999, TRUE, FALSE, 'Lyons & Hwy 201 Reverse 07 (Sprint) >');
INSERT INTO SOAPBOX.EVENT (ID, EVENTMODEID, MINLEVEL, MAXLEVEL, MINCARCLASSRATING, MAXCARCLASSRATING, ISENABLED, ISLOCKED, NAME)
VALUES (535, 9, 1, 70, 0, 999, TRUE, FALSE, 'Chinatown Delivery Reverse 08 (Sprint) >');