CREATE TABLE IF NOT EXISTS BASKETDEFINITION (
  PRODUCTID     VARCHAR(255),
  OWNEDCARTRANS LONGTEXT,

  PRIMARY KEY (PRODUCTID)
)
  CHARSET = utf8;


CREATE TABLE IF NOT EXISTS CARSLOT (
  ID            BIGINT NOT NULL AUTO_INCREMENT,
  OWNEDCARTRANS LONGTEXT,
  PERSONAID     BIGINT NOT NULL,

  PRIMARY KEY (ID)
)
  CHARSET = utf8;

CREATE TABLE IF NOT EXISTS CATEGORY (
  IDCATEGORY           BIGINT NOT NULL AUTO_INCREMENT,
  CATALOGVERSION       INT    NOT NULL,
  CATEGORIES           LONGTEXT,
  DISPLAYNAME          VARCHAR(255),
  FILTERTYPE           INT    NOT NULL,
  ICON                 VARCHAR(255),
  ID                   BIGINT NOT NULL,
  LONGDESCRIPTION      TEXT,
  NAME                 VARCHAR(255),
  PRIORITY             INT    NOT NULL,
  SHORTDESCRIPTION     TEXT,
  SHOWINNAVIGATIONPANE BOOL,
  SHOWPROMOPAGE        BOOL,
  WEBICON              VARCHAR(255),
  PRIMARY KEY (IDCATEGORY)
)
  CHARSET = utf8;

CREATE TABLE IF NOT EXISTS CHAT_ROOM (
  ID        BIGINT NOT NULL AUTO_INCREMENT,
  AMOUNT    INT,
  LONGNAME  VARCHAR(255),
  SHORTNAME VARCHAR(255),

  PRIMARY KEY (ID)
)
  CHARSET = utf8;

CREATE TABLE IF NOT EXISTS EVENT (
  ID                BIGINT NOT NULL AUTO_INCREMENT,
  EVENTMODEID       INT    NOT NULL,
  ISENABLED         BOOL,
  ISLOCKED          BOOL,
  MAXCARCLASSRATING INT,
  MAXLEVEL          INT,
  MINCARCLASSRATING INT,
  MINLEVEL          INT,
  `NAME`            TEXT,

  PRIMARY KEY (ID)
)
  CHARSET = utf8;
CREATE TABLE IF NOT EXISTS EVENT_DATA (
  ID                                   BIGINT  NOT NULL AUTO_INCREMENT,
  ALTERNATEEVENTDURATIONINMILLISECONDS BIGINT  NOT NULL,
  BESTLAPDURATIONINMILLISECONDS        BIGINT  NOT NULL,
  BUSTEDCOUNT                          INTEGER NOT NULL,
  CARID                                BIGINT  NOT NULL,
  COPSDEPLOYED                         INTEGER NOT NULL,
  COPSDISABLED                         INTEGER NOT NULL,
  COPSRAMMED                           INTEGER NOT NULL,
  COSTTOSTATE                          INTEGER NOT NULL,
  DISTANCETOFINISH                     FLOAT   NOT NULL,
  EVENTDURATIONINMILLISECONDS          BIGINT  NOT NULL,
  EVENTMODEID                          INTEGER NOT NULL,
  EVENTSESSIONID                       BIGINT,
  FINISHREASON                         INTEGER NOT NULL,
  FRACTIONCOMPLETED                    FLOAT   NOT NULL,
  HACKSDETECTED                        BIGINT  NOT NULL,
  HEAT                                 FLOAT   NOT NULL,
  INFRACTIONS                          INTEGER NOT NULL,
  LONGESTJUMPDURATIONINMILLISECONDS    BIGINT  NOT NULL,
  NUMBEROFCOLLISIONS                   INTEGER NOT NULL,
  PERFECTSTART                         INTEGER NOT NULL,
  PERSONAID                            BIGINT,
  RANK                                 INTEGER NOT NULL,
  ROADBLOCKSDODGED                     INTEGER NOT NULL,
  SPIKESTRIPSDODGED                    INTEGER NOT NULL,
  SUMOFJUMPSDURATIONINMILLISECONDS     BIGINT  NOT NULL,
  TOPSPEED                             FLOAT   NOT NULL,
  EVENTID                              INTEGER,

  PRIMARY KEY (ID)
)
  CHARSET = utf8;

CREATE TABLE IF NOT EXISTS EVENT_SESSION (
  ID      BIGINT NOT NULL AUTO_INCREMENT,
  EVENTID INTEGER,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS INVITE_TICKET (
  ID           BIGINT NOT NULL AUTO_INCREMENT,
  DISCORD_NAME VARCHAR(255),
  TICKET       VARCHAR(255),
  USERID       BIGINT,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LEVEL_REP (
  LEVEL    BIGINT NOT NULL AUTO_INCREMENT,
  EXPPOINT BIGINT,

  PRIMARY KEY (LEVEL)
);

CREATE TABLE IF NOT EXISTS LOBBY (
  ID                 BIGINT NOT NULL AUTO_INCREMENT,
  ISPRIVATE          BOOL,
  LOBBYDATETIMESTART TIMESTAMP,
  PERSONAID          BIGINT,
  EVENTID            INTEGER,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS LOBBY_ENTRANT (
  ID        BIGINT AUTO_INCREMENT NOT NULL,
  GRIDINDEX INTEGER               NOT NULL,
  LOBBYID   BIGINT,
  PERSONAID BIGINT,

  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS LOGIN_ANNOUNCEMENT (
  ID       BIGINT AUTO_INCREMENT NOT NULL,
  IMAGEURL VARCHAR(255),
  TARGET   VARCHAR(255),
  TYPE     VARCHAR(255),

  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ONLINE_USERS (
  ID            INTEGER NOT NULL,
  NUMBEROFUSERS INTEGER NOT NULL,

  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PERSONA (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BOOST DOUBLE NOT NULL,
  CASH DOUBLE NOT NULL,
  CURCARINDEX INTEGER NOT NULL,
  ICONINDEX INTEGER NOT NULL,
  LEVEL INTEGER NOT NULL,
  MOTTO VARCHAR(255),
  NAME VARCHAR(255),
  PERCENTTOLEVEL FLOAT NOT NULL,
  RATING DOUBLE NOT NULL,
  REP DOUBLE NOT NULL,
  REPATCURRENTLEVEL INTEGER NOT NULL,
  SCORE INTEGER NOT NULL,
  USERID BIGINT,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BUNDLEITEMS VARCHAR(255),
  CATEGORYID VARCHAR(255),
  CATEGORYNAME VARCHAR(255),
  CURRENCY VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  DURATIONMINUTE INTEGER NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  HASH BIGINT,
  ICON VARCHAR(255),
  LEVEL INTEGER NOT NULL,
  LONGDESCRIPTION VARCHAR(255),
  MINLEVEL INTEGER NOT NULL,
  PREMIUM BOOLEAN NOT NULL,
  PRICE FLOAT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRODUCTID VARCHAR(255),
  PRODUCTTITLE VARCHAR(255),
  PRODUCTTYPE VARCHAR(255),
  SECONDARYICON VARCHAR(255),
  USECOUNT INTEGER NOT NULL,
  VISUALSTYLE VARCHAR(255),
  WEBICON VARCHAR(255),
  WEBLOCATION VARCHAR(255),

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS RECOVERY_PASSWORD (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  EXPIRATIONDATE TIMESTAMP,
  ISCLOSE BOOLEAN,
  RANDOMKEY VARCHAR(255),
  USERID BIGINT,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS REPORT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  ABUSERPERSONAID BIGINT,
  CHATMINUTES INTEGER,
  CUSTOMCARID INTEGER,
  DESCRIPTION VARCHAR(255),
  HACKSDETECTED BIGINT,
  PERSONAID BIGINT,
  PETITIONTYPE INTEGER,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS SERVER_INFO (
  MESSAGESRV VARCHAR(1000) NOT NULL,
  COUNTRY VARCHAR(255),
  ADMINLIST VARCHAR(255),
  BANNERURL VARCHAR(255),
  DISCORDURL VARCHAR(255),
  FACEBOOKURL VARCHAR(255),
  HOMEPAGEURL VARCHAR(255),
  NUMBEROFREGISTERED INTEGER,
  OWNERLIST VARCHAR(255),
  SERVERNAME VARCHAR(255),
  TIMEZONE INTEGER
);

CREATE TABLE IF NOT EXISTS TOKEN_SESSION (
  ID VARCHAR(255) NOT NULL,
  ACTIVELOBBYID BIGINT,
  ACTIVEPERSONAID BIGINT,
  EXPIRATIONDATE TIMESTAMP,
  PREMIUM BOOLEAN NOT NULL,
  RELAYCRYPTOTICKET VARCHAR(255),
  USERID BIGINT,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  EMAIL VARCHAR(255),
  PASSWORD VARCHAR(50),
  PREMIUM BOOLEAN NOT NULL,

  PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS VINYLPRODUCT (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  BUNDLEITEMS VARCHAR(255),
  CATEGORYID VARCHAR(255),
  CATEGORYNAME VARCHAR(255),
  CURRENCY VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  DURATIONMINUTE INTEGER NOT NULL,
  ENABLED BOOLEAN NOT NULL,
  HASH BIGINT NOT NULL,
  ICON VARCHAR(255),
  LEVEL INTEGER NOT NULL,
  LONGDESCRIPTION VARCHAR(255),
  MINLEVEL INTEGER NOT NULL,
  PREMIUM BOOLEAN NOT NULL,
  PRICE FLOAT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  PRODUCTID VARCHAR(255),
  PRODUCTTITLE VARCHAR(255),
  PRODUCTTYPE VARCHAR(255),
  SECONDARYICON VARCHAR(255),
  USECOUNT INTEGER NOT NULL,
  VISUALSTYLE VARCHAR(255),
  WEBICON VARCHAR(255),
  WEBLOCATION VARCHAR(255),
  PARENTCATEGORYID BIGINT,

  PRIMARY KEY (ID)
);